services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - "8086:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=203040
      - MYSQL_DATABASE=dbFromCompose
      
    depends_on:
      - nginx